spring.config.activate.on-profile=prod
server.port=${PORT:8080}


spring.data.mongodb.uri=${MONGODB_URI}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
server.servlet.context-path=/api/v1.0

spring.ai.google.genai.api-key=${GEMINI_KEY}
spring.ai.google.genai.chat.model=${GEMINI_MODEL}
spring.ai.google.genai.chat.temperature=${GEMINI_TEMPERATURE}

clerk.issuer=${CLERK_ISSUER}
clerk.jwks-url=${CLERK_JWKS_URL}
clerk.webhook.secret=${CLERK_WEBHOOK_SECRET}

spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.endpoints.web.base-path=/actuator
